env:
  node: true
  jest: true
  browser: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:react/recommended'

settings:
  import/resolver: webpack
  react:
    version: '16.6.0'

rules:
  no-console: 1
  max-len: 1
  import/prefer-default-export: 0
  operator-linebreak: 0
